### ISSUE TITLE
fix build after Morgan added

### ISSUE THREAD

**Issue by neSpecc** [codex-team/hawk.api.nodejs#536]
After merging of #535 build is failed: https://github.com/codex-team/hawk.api.nodejs/actions/runs/18351556975/job/52272616011?pr=533

```
error TS7016: Could not find a declaration file for module 'morgan'. '/usr/src/app/node_modules/morgan/index.js' implicitly has an 'any' type.
```

Fix this problem and check if `yarn build` is being passed correctly
